"""add email_verified to users

Revision ID: abfaf96b60ec
Revises: 899e3e329b68
Create Date: 2026-02-28 18:14:22.357991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'abfaf96b60ec'
down_revision: Union[str, None] = '899e3e329b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_email', table_name='admins')
    op.drop_table('admins')
    op.drop_table('admin_logs')
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.create_table('admin_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('target_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_id', sa.VARCHAR(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_superadmin', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admins_email', 'admins', ['email'], unique=1)
    # ### end Alembic commands ###
