"""add indexes to chat_sessions

Revision ID: e525e1bf70e8
Revises: 2b6d6fbf3f84
Create Date: 2026-03-05 12:53:44.189477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e525e1bf70e8'
down_revision: Union[str, None] = '2b6d6fbf3f84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('admin_logs')
    op.drop_index('ix_admins_email', table_name='admins')
    op.drop_table('admins')
    op.create_index('idx_chat_session_tenant_updated', 'chat_sessions', ['tenant_id', 'updated_at'], unique=False)
    op.create_index('idx_chat_session_updated', 'chat_sessions', ['updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_session_updated', table_name='chat_sessions')
    op.drop_index('idx_chat_session_tenant_updated', table_name='chat_sessions')
    op.create_table('admins',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=True),
    sa.Column('is_superadmin', sa.BOOLEAN(), nullable=True),
    sa.Column('two_factor_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('last_login', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admins_email', 'admins', ['email'], unique=1)
    op.create_table('admin_logs',
    sa.Column('id', sa.VARCHAR(), nullable=False),
    sa.Column('admin_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('target_type', sa.VARCHAR(), nullable=True),
    sa.Column('target_id', sa.VARCHAR(), nullable=True),
    sa.Column('details', sqlite.JSON(), nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
