"""add client_id to chat_sessions

Revision ID: f955d39651c3
Revises: c7d5d0cf3ae0
Create Date: 2026-02-24 19:14:44.789754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f955d39651c3'
down_revision: Union[str, None] = 'c7d5d0cf3ae0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('client_id', sa.String(), nullable=True))
    op.create_index('idx_chat_session_client_id', 'chat_sessions', ['client_id'], unique=False)
    op.create_index('idx_chat_session_tenant_created', 'chat_sessions', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_sessions_client_id'), 'chat_sessions', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_sessions_client_id'), table_name='chat_sessions')
    op.drop_index('idx_chat_session_tenant_created', table_name='chat_sessions')
    op.drop_index('idx_chat_session_client_id', table_name='chat_sessions')
    op.drop_column('chat_sessions', 'client_id')
    # ### end Alembic commands ###
